
class constants:
    ADAPTIVE_THRESHOLD_BLOCK_SIZE = 15
    ADAPTIVE_THRESHOLD_CONSTANT = -2
    RESIZE_MAX_AREA  = 50000
    PERCENT_CONFIDENCE_THRESHOLD=5.0
    SCALE = 15
    POOL_SIZE= 5
    BUFFER_CAPACITY = 3